Models/ErrorViewModel.cs
using System;

namespace bono.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/bono.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BONO.Models
{
    [Table ("registro_bono")]
    public class bono
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        
        [Required(ErrorMessage = "Por favor, ingrese el Nombre")]
        [Display(Name="Nombre")]
        [Column("Nombre")]
        public String Name { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese el Apellido")]
        [Display(Name="Apellido")]
        [Column("Apellido")]
        public String LastName { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese el Distrito")]
        [Display(Name="Distrito")]
        [Column("Distrito")]
        public String Distrito { get; set; }
        
        
        [Required(ErrorMessage = "Por favor, ingrese su banco")]
        [Display(Name="banco")]
        public String banco { get; set; }
        [Column("banco")]


        [Required(ErrorMessage = "Por favor, ingrese su Edad")]
        [Display(Name="Edad")]       
        public int Edad { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese su genero")]
        [Display(Name="genero")]  
        public String genero { get; set; }

       [NotMapped]
        public String Response { get; set; }

    }
}

Controllers/BonoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using bono.Models;
using bono.Data;


namespace BONO.Controllers
{
    public class BonoController : Controller
    {

       private readonly ILogger<BonoController> _logger;

       private readonly DatabaseContext _context;

        public BonoController(ILogger<BonoController> logger, DatabaseContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(BONO.Models.bono objbono){
            if (ModelState.IsValid)
            {
                _context.Add(objbono);
                _context.SaveChanges();      
                
                objbono.Response = "AVILCAYÂÑEZ";
            }
            return View("index", objbono);
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using bono.Models;

namespace bono.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bono</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">bono</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="bono" asp-action="Index">bono</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - bono - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/bono/index.cshtml
@model BONO.Models.bono

@{
    ViewData["Title"] = "BONO";
}

<div class="row">
    <div class="col-md-4">  
        <h1 class="display-4">Hecho por ALEJANDRO VILCA</h1>
        <form asp-controller="Bono" asp-action="Registrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>    

            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div> 

            <div class="form-group">
                <label asp-for="Distrito" class="control-label"></label>
                <input asp-for="Distrito" class="form-control" />
                <span asp-validation-for="Distrito" class="text-danger"></span>
            </div>   

              <label>BANCO</label>
            <select asp-for="banco">
                <option >BBVA</option>
                <option >BCP</option>
                <option >MiBanco</option>                               
            </select>
            <br/>  

            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>  

            <div class="form-group">
            <input asp-for="genero" type="radio" id="male" name="gender" value="male">
            <label asp-for="genero" for="male">Male</label><br>
            <input asp-for="genero" type="radio" id="female" name="gender" value="female">
            <label asp-for="genero" for="female">Female</label><br>
            <input asp-for="genero" type="radio" id="other" name="gender" value="other">
            <label asp-for="genero" for="other">Other</label>      
            </div>

            <div class="form-group">
                 <button type="submit" class="btn btn-primary">Registrar</button> 
            </div>                

        </form>
            
        <td>@Html.DisplayTextFor(model => model.Response)</td>    
    
    </div>
</div>